import { styled } from '@/stitches.config'

export const SkewButton = styled('button', {
  position: 'relative',
  zIndex: 1,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  textAlign: 'center',
  minWidth: 120,
  height: 32,
  background: 'transparent',
  outline: 'none',
  border: 'none',
  fontWeight: 'bold',
  letterSpacing: '.145rem',
  textTransform: 'uppercase',
  transition: 'all 100ms ease-in-out',
  color: '$blue',
  cursor: 'pointer',
  '&::before': {
    transform: 'skewX(-30deg)',
    content: '""',
    position: 'absolute',
    inset: 0,
    zIndex: -1,
    background: 'transparent',
    border: '2px solid $blue',
    borderRadius: 4,
  },
  '&::after': {
    transition: 'all 140ms ease-in-out',
    transform: 'skewX(-30deg) scaleX(0)',
    transformOrigin: 'left center',
    content: '""',
    position: 'absolute',
    inset: 0,
    zIndex: -2,
    border: '2px solid $blue',
    borderRadius: 4,
    background: '$blue',
  },
  '&:hover&::after': {
    transform: 'skewX(-30deg) scaleX(1)',
  },
  '&:hover': {
    color: '$background',
  },
})
